### PR TITLE
F# Interactive Integration

### LINKED ISSUE #9: Add FSI Support
Since .NET Core 3.0 is officially out now, I'd like to add support for F# Interactive to Ionide-vim.

We'll (of course) utilize `dotnet fsi` instead of the one shipped with Mono.

### PR DESCRIPTION
**Pull request by cannorin**
Closes #9.

TODO:
- [x] Functionalities
  - [x] Open and toggle FSI in split window
  - [x] Send line/selection
  - [x] Send whole buffer (file)
  - [ ] ~~Send references from project (if possible)~~ => https://github.com/fsharp/FsAutoComplete/pull/442
- [x] Commands
  - [x] `:FsiEval`
  - [x] `:FsiEvalBuffer`
  - [x] `:FsiReset`
  - [x] `:FsiShow`
  - [ ] ~~And more~~
- [x] Customization via settings
  - [x] FSI executable location: `g:fsharp#fsharp_interactive_command`
  - [x] FSI window split style
  - [x] Key binding
  - [x] Focus to FSI on sending line/selection or don't
  - [ ] ~~And more~~
- [x] Docs

### CODE REVIEW

**Comment by Krzysztof-Cieslak** [comment]
Please keep in mind that current master of FSAC has totally broken the script file experience. We try to fix that in https://github.com/fsharp/FsAutoComplete/pull/466

**Comment by cannorin** [comment]
@Krzysztof-Cieslak Hmm. Could you tell me which is the latest non-broken commit (if you have time)?

**Comment by cannorin** [comment]
Almost done. Any suggestions for more features/commands?

**Comment by cannorin** [comment]
As we need https://github.com/fsharp/FsAutoComplete/pull/442 to implement "send references from project" feature, I'll merge this as-is for now and implement additional features later.

**Pull request merged**
